version: "3.5"
services:
  optimization_app:
    build: .
    image: "optimization_app:1"
    container_name: "optimization_app"
    command: >
      sh -c "cd src &&
             python3 manage.py migrate --no-input &&
             python3 manage.py createadmin &&
             python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - '8080:8080'
    networks:
      backend:
    environment:
      - DB_NAME=optimization_app
      - DB_USER=optimization_app
      - DB_PASSWORD=12345678
      - DB_HOST=database
      - DB_PORT=5432
      - ADMIN_NAME=adm2
      - ADMIN_PASSWORD=adm2
    volumes:
      - ./src:/service/src
    restart: unless-stopped
    depends_on:
      - database

  database:
      image: "postgres:13"
      container_name: "db_postgres"
      command: ["postgres", "-c", "log_statement=all",
                "-c", "log_destination=stderr"]
      networks:
        backend:
      environment:
        - POSTGRES_DB=optimization_app
        - POSTGRES_USER=optimization_app
        - POSTGRES_PASSWORD=12345678
      volumes:
         - postgres:/var/lib/postgresql/data
      restart: unless-stopped

  redis:
    image: 'redis:7'
    container_name: 'redis'
    hostname: 'redis'
    networks:
      - backend
    restart: unless-stopped

  worker1:
    build: .
    image: 'worker1'
    container_name: 'worker1'
    hostname: 'worker1'
    command: >
      sh -c "cd src && celery -A celery_app.app worker --loglevel=info"
    networks:
      - backend
    environment:
      - DB_NAME=optimization_app
      - DB_USER=optimization_app
      - DB_PASSWORD=12345678
      - DB_HOST=database
      - DB_PORT=5432
      - ADMIN_NAME=adm2
      - ADMIN_PASSWORD=adm2
    volumes:
      - ./src:/service/src
    depends_on:
      - redis
      - database
    restart: unless-stopped

  worker2:
    build: .
    image: 'worker2'
    container_name: 'worker2'
    hostname: 'worker2'
    command: >
      sh -c "cd src && celery -A celery_app.app worker --loglevel=info"
    networks:
      - backend
    environment:
      - DB_NAME=optimization_app
      - DB_USER=optimization_app
      - DB_PASSWORD=12345678
      - DB_HOST=database
      - DB_PORT=5432
      - ADMIN_NAME=adm2
      - ADMIN_PASSWORD=adm2
    volumes:
      - ./src:/service/src
    depends_on:
      - redis
      - database
    restart: unless-stopped

  flower:
    build: .
    hostname: 'flower'
    container_name: 'flower'
    command: >
      sh -c "cd src && celery -A celery_app.app flower"
    ports:
      - '5555:5555'
    networks:
      - backend
    volumes:
      - ./src:/service/src
    depends_on:
      - redis
    restart: unless-stopped
volumes:
  postgres:
networks:
  backend:
    driver: bridge
