# Generated by Django 4.2.3 on 2023-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tariffplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffplan',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
